Document: natron
Title: Debian natron Manual
Author: <insert document author here>
Abstract: This manual describes what natron is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/natron/natron.sgml.gz

Format: postscript
Files: /usr/share/doc/natron/natron.ps.gz

Format: text
Files: /usr/share/doc/natron/natron.text.gz

Format: HTML
Index: /usr/share/doc/natron/html/index.html
Files: /usr/share/doc/natron/html/*.html
